// Added buildscript to fetch external plugins (Parchment & Mixin)
buildscript {
    repositories {
        maven { 
            url = "https://maven.minecraftforge.net" 
        }

        maven { 
            url = "https://maven.parchmentmc.org" 
        }

        maven { 
            url = "https://repo.spongepowered.org/repository/maven-public/" 
        }

        mavenCentral()
    }

    dependencies {
        classpath "org.parchmentmc:librarian:1.+"
        classpath "org.spongepowered:mixingradle:0.7-SNAPSHOT"
    }
}


plugins {
    id "eclipse"
    id "idea"
    id "maven-publish"
    id "net.minecraftforge.gradle" version "[6.0,6.2)"
}


// Apply external plugins
apply plugin: "org.parchmentmc.librarian.forgegradle"
apply plugin: "org.spongepowered.mixin"


version = mod_version
group = mod_group_id


base {
    archivesName = mod_id
}


// Minecraft 1.18+ uses Java 17
java.toolchain.languageVersion = JavaLanguageVersion.of(17)


println "Java: ${System.getProperty 'java.version'}, JVM:${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch:${System.getProperty 'os.arch'}"



minecraft {

    // Parchment mappings for Minecraft 1.20.1
    mappings channel: "parchment", version: "2023.06.26-1.20.1"

    copyIdeResources = true


    runs {

        configureEach {

            workingDirectory project.file("run")

            property "forge.logging.markers", "REGISTRIES"
            property "forge.logging.console.level", "debug"


            // Critical fix:
            // Forces Mixin to ignore ALL refmap errors,
            // including those generated by Valkyrien Skies 2.


            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }


        client {

            property "forge.enabledGameTestNamespaces", mod_id

        }


        server {

            property "forge.enabledGameTestNamespaces", mod_id

            args "--nogui"

        }


        gameTestServer {

            property "forge.enabledGameTestNamespaces", mod_id

        }


        data {

            workingDirectory project.file("run-data")

            args "--mod", mod_id,
                 "--all",
                 "--output", file("src/generated/resources/"),
                 "--existing", file("src/main/resources/")

        }

    }

}



// Mixin configuration
mixin {

    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"

}



// Include generated data resources
sourceSets.main.resources {

    srcDir "src/generated/resources"

}



repositories {

    flatDir {
        dir "libs"
    }


    mavenCentral()


    maven {
        url = "https://maven.minecraftforge.net"
    }


    maven {
        name = "henkelmax"
        url = "https://maven.maxhenkel.de/repository/public"
    }


    maven {
        name = "Valkyrien Skies"
        url = "https://maven.valkyrienskies.org"
    }

    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }


    maven {
        url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/"
    }

}




dependencies {


    // Minecraft + Forge
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"



    // GeckoLib 4.4.7
    implementation fg.deobf(
        "software.bernie.geckolib:geckolib-forge-1.20.1:4.4.7"
    )



    // Vic's Point Blank
    implementation fg.deobf(
        "maven.modrinth:vics-point-blank:1.11.1"
    )



    // Mixin processor
    annotationProcessor(
        "org.spongepowered:mixin:0.8.5:processor"
    )



    // RNNoise
    implementation(
        "de.maxhenkel.rnnoise4j:rnnoise4j:2.1.2"
    )

    implementation "thedarkcolour:kotlinforforge:4.11.0"

    // Valkyrien Skies Integration
    implementation fg.deobf(
        "blank:valkyrienskies-120:2.3.0-beta.5tt22x2"
    )

    compileOnly(
        "org.valkyrienskies.core:api:1.1.0+"
    )

}





tasks.named("processResources", ProcessResources).configure {


    def replaceProperties = [

        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,

        forge_version: forge_version,
        forge_version_range: forge_version_range,

        loader_version_range: loader_version_range,


        mod_id: mod_id,
        mod_name: mod_name,
        mod_license: mod_license,
        mod_version: mod_version,

        mod_authors: mod_authors,
        mod_description: mod_description

    ]


    inputs.properties replaceProperties


    filesMatching([
        "META-INF/mods.toml",
        "pack.mcmeta"
    ]) {

        expand replaceProperties + [project: project]

    }

}





tasks.named("jar", Jar).configure {


    manifest {

        attributes([

            "Specification-Title": mod_id,

            "Specification-Vendor": mod_authors,

            "Specification-Version": "1",


            "Implementation-Title": project.name,

            "Implementation-Version": project.jar.archiveVersion,

            "Implementation-Vendor": mod_authors,


            "Implementation-Timestamp":
                new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),


            "MixinConfigs":
                "${mod_id}.mixins.json"

        ])

    }


    finalizedBy "reobfJar"

}





publishing {


    publications {

        register("mavenJava", MavenPublication) {

            artifact jar

        }

    }


    repositories {

        maven {

            url = "file://${project.projectDir}/mcmodsrepo"

        }

    }

}





tasks.withType(JavaCompile).configureEach {

    options.encoding = "UTF-8"

}